(()=>{"use strict";function isWebp(){const testWebP=(callback)=>{const webP=new Image();webP.onload=webP.onerror=()=>callback(webP.height===2);webP.src="data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA};testWebP((support)=>{document.documentElement.classList.add(support?"webp":"no-webp")})}
let bodyLockStatus=!0;const bodyLockToggle=(delay=500)=>document.documentElement.classList.contains("lock")?bodyUnlock(delay):bodyLock(delay);const bodyUnlock=(delay=500)=>{if(!bodyLockStatus)return;const body=document.body;const lockPadding=document.querySelectorAll("[data-lp]");setTimeout(()=>{lockPadding.forEach((el)=>(el.style.paddingRight="0px"));body.style.paddingRight="0px";document.documentElement.classList.remove("lock")},delay);bodyLockStatus=!1;setTimeout(()=>(bodyLockStatus=!0),delay)};const bodyLock=(delay=500)=>{if(!bodyLockStatus)return;const body=document.body;const lockPadding=document.querySelectorAll("[data-lp]");const paddingValue=window.innerWidth-document.querySelector(".wrapper").offsetWidth+"px";lockPadding.forEach((el)=>(el.style.paddingRight=paddingValue));body.style.paddingRight=paddingValue;document.documentElement.classList.add("lock");bodyLockStatus=!1;setTimeout(()=>(bodyLockStatus=!0),delay)};function menuInit(){const iconMenu=document.querySelector(".icon-menu");if(!iconMenu)return;document.addEventListener("click",(e)=>{if(bodyLockStatus&&e.target.closest(".icon-menu")){bodyLockToggle();document.documentElement.classList.toggle("menu-open")}})}
class DynamicAdapt{constructor(type){this.type=type}
init(){this.objects=[];this.daClassname="_dynamic_adapt_";this.nodes=[...document.querySelectorAll("[data-da]")];this.nodes.forEach((node)=>{const[dest,bp="767",place="last"]=node.dataset.da.trim().split(",");const obj={element:node,parent:node.parentNode,destination:document.querySelector(dest.trim()),breakpoint:bp.trim(),place:place.trim(),index:this.indexInParent(node.parentNode,node),};this.objects.push(obj)});this.arraySort(this.objects);this.mediaQueries=this.objects.map(({breakpoint})=>`(${this.type}-width: ${breakpoint}px),${breakpoint}`).filter((item,i,self)=>self.indexOf(item)===i);this.mediaQueries.forEach((media)=>{const[mq,bp]=media.split(",");const matchMedia=window.matchMedia(mq);const objs=this.objects.filter(({breakpoint})=>breakpoint===bp);matchMedia.addEventListener("change",()=>this.mediaHandler(matchMedia,objs));this.mediaHandler(matchMedia,objs)})}
mediaHandler(matchMedia,objs){if(matchMedia.matches){objs.forEach((obj)=>this.moveTo(obj.place,obj.element,obj.destination))}else{objs.forEach(({parent,element,index})=>{if(element.classList.contains(this.daClassname))
this.moveBack(parent,element,index)})}}
moveTo(place,element,destination){element.classList.add(this.daClassname);if(place==="last"||place>=destination.children.length){destination.append(element)}else if(place==="first"){destination.prepend(element)}else{destination.children[place].before(element)}}
moveBack(parent,element,index){element.classList.remove(this.daClassname);parent.children[index]?parent.children[index].before(element):parent.append(element)}
indexInParent(parent,element){return[...parent.children].indexOf(element)}
arraySort(arr){arr.sort((a,b)=>{if(a.breakpoint===b.breakpoint){if(a.place===b.place)return 0;if(a.place==="first"||b.place==="last")return this.type==="min"?-1:1;if(a.place==="last"||b.place==="first")return this.type==="min"?1:-1}
return this.type==="min"?a.breakpoint-b.breakpoint:b.breakpoint-a.breakpoint})}}
function animationsBlocksHeader(){const header=document.querySelector("header");window.addEventListener("scroll",()=>{header.classList.toggle("header__color",window.pageYOffset>40)})}
const iconBtnBenefits=document.querySelector(".icon-inner-benefits");if(iconBtnBenefits){iconBtnBenefits.addEventListener("click",()=>document.documentElement.classList.toggle("sayde-active"))}
const da=new DynamicAdapt("max");da.init();isWebp();menuInit();animationsBlocksHeader()})()